# aliases
alias ..='cd ..'                                
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias back='cd $OLDPWD'
alias c='clear'
alias i='sudo apt install'
alias u='sudo apt update'
alias ug='sudo apt upgrade'
alias chmod="chmod -c"
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -'
alias tree='tree -L 2'
alias rsync='rsync -avzh --progress --stats'
alias shutdown="sudo shutdown -h 1"
alias apt='sudo apt'
alias wx='cd /mnt/c/Users/bmorgan'
alias update='sudo apt update && sudo apt upgrade -y && sudo apt-get clean'
alias shred='sudo shred -fvuzn 5'
alias calias='cat ~/.bash_aliases'
alias reload='source ~/.bash_aliases'
alias ssha='eval "$(ssh-agent)"; ssh-add ~/.ssh/ansible '
alias dfl='df -lh | grep -vw snap | grep -v loop | grep -v tmpfs'
alias dname='docker ps --format '{{.Names}}''
alias nmap='nmap -A -T4'
alias ps='ps -e | more'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'
alias diff='diff -y'
alias la='ls -alh'
alias ping='ping -c 5'
alias calias='cat ~/.bash_aliases'
alias sch='sudo du -sch * | sort -h'
alias wget='wget -c'
# View Git status.
alias gs='git status'
alias sshost='grep ^Host ~/.ssh/config'
# Add all files to Git.
alias gaa='git add --all'
# Commit changes to the code.
alias gc='git commit'
alias gpull='git pull'
alias gpush='git push'
# View the Git log.
alias gl='git log --oneline'
# View the difference.
alias gd='git diff'

## get top process eating memory
alias mem5='ps auxf | sort -nr -k 4 | head -5'
alias mem10='ps auxf | sort -nr -k 4 | head -10'

alias mem5='ps auxf | sort -nr -k 4 | head -5'       
alias cpu5='ps auxf | sort -nr -k 3 | head -5'                                      
alias cpu10='ps auxf | sort -nr -k 3 | head -10'

## List largest directories (aka "ducks")
alias dir5='du -cksh * | sort -hr | head -n 5'
alias dir10='du -cksh * | sort -hr | head -n 10'

# Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root' 


