---
- hosts: localhost
  connection: local
  become: true
 
  tasks:
  - name: pre-run | update package cache (arch)
    tags: always
    pacman: update_cache=yes
    changed_when: False
    when: ansible_distribution == "Archlinux"

  - name: pre-run | update package cache (debian, etc)
    tags: always
    apt: update_cache=yes
    changed_when: False
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        - vim-nox
        - python3-psutil

  - name: copy custom .bashrc file
    copy:
      src: files/bashrc
      dest: /home/bmorgan/.bashrc
      owner: bmorgan
      group: bmorgan

  - name: add ansible user
    user:
      name: itst
      system: yes
 
  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_itst
      dest: /etc/sudoers.d/itst
      owner: root
      group: root
      mode: 0440
 
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: itst
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/morganbo85/ansible_dt.git
