---
- hosts: localhost
  connection: local
  become: true
 
  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        - vim-nox
        - python3-psutil

  - name: copy custom .bashrc file
    copy:
      src: files/bashrc
      dest: /home/bmorgan/.bashrc
      owner: bmorgan
      group: bmorgan
