---
# tasks to complete before running roles
- hosts: localhost
  connection: local
  become: true
 
  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        - vim-nox
