- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: ansible
    minute: "*/10"
    job: "eval $(ssh-agent -s) && ssh-add ~/.ssh/id_ed25519 && /usr/bin/ansible-pull -o -U git@github.com:morganbo85/ansible_dt.git -i localhost"
