- name: create itst and sudo group
  ansible.builtin.group:
    name: "sudo"
    state: present

- name: create itst user
  user:
    name: itst
    system: yes
    groups: "sudo"
    create_home: true
    home: "/home/itst"
    shell: "/bin/bash"

- name: Ensure the directory /.ssh exists
  ansible.builtin.file:
    path: /home/itst/.ssh
    state: directory

- name: copy custom authorized_key file
  copy:
    src: files/itst/authorized_keys
    dest: /home/bmorgan/.ssh/authorized_keys
    owner: itst
    group: itst

- name: updating itst password
  user:
   name: itst
   update_password: always
   password: $6$SCWLFwCWsCnxBFzu$S/mJh15OqsPop760zkANMm.rh9kVOGunIrOUfgTsa4NUKLW.RAAVtTuolMqUSLWGxwhS4LWkvTCSJbwUh8bkC.

- name: copy custom .bashrc file
  copy:
    src: files/itst/bashrc
    dest: /home/itst/.bashrc
    owner: itst

- name: copy custom .bash_prompt file
  copy:
    src: files/itst/bash_prompt
    dest: /home/itst/.bash_prompt
    owner: itst

- name: copy custom bash_aliases file
  copy:
    src: files/itst/bash_aliases
    dest: /home/itst/.bash_aliases
    owner: itst

- name: copy sudoer_itst
  copy:
    src: files/itst/ssh/sudoer_itst
    dest: /etc/sudoers.d/itst
    owner: root
    group: root
    mode: 0440

