- name: copy custom .bashrc file
  copy:
    src: files/bashrc
    dest: /home/bmorgan/.bashrc
    owner: bmorgan
    group: bmorgan

- name: copy custom bash_aliases file
  copy:
    src: files/bash_aliases
    dest: /home/bmorgan/.bash_aliases
    owner: bmorgan
    group: bmorgan

- name: copy custom authorized_key file
  copy:
    src: files/authorized_keys
    dest: /home/bmorgan/.ssh/authorized_keys
    owner: bmorgan
    group: bmorgan

- name: copy custom profile.d file
  copy:
    src: files/bmorgan.sh
    dest: /etc/profile.d/bmorgan.sh
    owner: root
    group: root
    mode: 0440

- name: copy custom sudoers.d file
  copy:
    src: files/sudoears_bmorgan
    dest: /etc/sudoers.d/bmorgan
    owner: root
    group: root
      mode: 0440

- name: copy custom tmux file
  copy:
    src: files/tmux.conf
    dest: /home/bmorgan/.tmux.conf
    owner: bmorgan
    group: bmorgan
